### ISSUE TITLE
Develop the audio recorder

### ISSUE THREAD

**Issue by caroldarski** [VanHackathon2017HueBR/presentation-builder#8]
Create audio recorder using plugin chrome;

**Comment by mateusmnc** [comment]
Using the following js a base for the recording functionality: https://webaudiodemos.appspot.com/AudioRecorder/js/recorderjs/recorder.js

**Comment by mateusmnc** [comment]
It's done!
Many things were made inside this task, such as the research, prototype, integration, core development, edit controls and the UI.
